### ISSUE TITLE
Re-ordering buttons

### ISSUE THREAD

**Issue by tpartner** [olleharstedt/ExtraQuickMenuItems#2]
Nice work Olle. 

Maybe I'm getting greedy but how about allowing re-ordering of the buttons? :)

**Comment by olleharstedt** [comment]
Hi!

Yes, this is already bothering me in my daily use. I want to add same functionality as in the Ubuntu unity interface (or Eve Online), where you can order buttons in-place.

**Comment by olleharstedt** [comment]
Fixed. Pull latest version of LS and the plugin, and deactivate and activate the plugin again. You should be able to sort using drag-and-drop in the quick-menu itself.
